import {
  Baby,
  Beer,
  BookOpen,
  Briefcase,
  Car,
  Coffee,
  Droplets,
  Dumbbell,
  Ellipsis,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  House,
  PawPrint,
  PiggyBank,
  Pill,
  Plane,
  Receipt,
  Scissors,
  Shirt,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  Star,
  Stethoscope,
  Ticket,
  TrainFront,
  Umbrella,
  Utensils,
  Wallet,
  Wifi,
  Zap,
  type LucideIcon,
} from 'lucide-react';

// 種類のアイコンの絵（moneyUtils の MONEY_ICONS の key と対応）。mobile版の
// `mobile/src/components/money/moneyIcons.ts` と同じ割り当て。
export const MONEY_ICON_COMPONENTS: Record<string, LucideIcon> = {
  home: House,
  sofa: Sofa,
  food: Utensils,
  grocery: ShoppingCart,
  cafe: Coffee,
  drink: Beer,
  power: Zap,
  gas: Flame,
  water: Droplets,
  daily: ShoppingBasket,
  beauty: Sparkles,
  clothes: Shirt,
  hair: Scissors,
  train: TrainFront,
  car: Car,
  fuel: Fuel,
  plane: Plane,
  phone: Smartphone,
  wifi: Wifi,
  medical: Stethoscope,
  pill: Pill,
  heart: Heart,
  ticket: Ticket,
  game: Gamepad2,
  book: BookOpen,
  sports: Dumbbell,
  baby: Baby,
  school: GraduationCap,
  gift: Gift,
  pet: PawPrint,
  wallet: Wallet,
  insurance: Umbrella,
  receipt: Receipt,
  salary: Briefcase,
  savings: PiggyBank,
  star: Star,
  other: Ellipsis,
};
